name: Secure Deploy to Netlify from Google Drive

on:
  repository_dispatch:
    types: [deploy-dashboard]

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: trial_env

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Google Drive dependencies
        run: pip install google-api-python-client google-auth

      - name: Download HTML from private Drive via service account
        run: python download_drive_file.py
        env:
          HTML_FILE_ID: ${{ github.event.client_payload.html_file_id }}
          GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}

      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Commit and push new dashboard file
        run: |
          dashboard_key=$(cat dashboard_key.txt)
          git add output_files/${dashboard_key}.html
          git commit -m "Add dashboard: ${dashboard_key}" || echo "No changes to commit"
          git push origin HEAD
